services:
  milvus:
    image: milvusdb/milvus:v2.2.5
    container_name: milvus_cpu
    ports:
      - "19530:19530"
      - "19121:19121"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - STANDALONE=true
    restart: unless-stopped

volumes:
  milvus_data: